language: node_js
node_js:
  - "10.13.0"
install: npm install
before_script: npm test
script: npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $DECK_DEPLOYMENT_TOKEN
  committer-from-gh: true
  local-dir: ./dist/
  on:
    branch: master