export const EVENT_TYPES = {
    CANVAS_MOUSE_DOWN: 'Deck.CanvasMouseDown',
    CANVAS_MOUSE_MOVE: 'Deck.CanvasMouseMove',
    CANVAS_MOUSE_OVER: 'Deck.CanvasMouseOver',
    CANVAS_MOUSE_OUT: 'Deck.CanvasMouseOut',
    CANVAS_MOUSE_UP: 'Deck.CanvasMouseUp',
    CANVAS_KEY_UP: 'Deck.CanvasKeyUp',
    CANVAS_KEY_DOWN: 'Deck.CanvasKeyDown',
    GRAPHIC_MOUSE_DOWN: 'Deck.GraphicMouseDown',
    GRAPHIC_MOUSE_MOVE: 'Deck.GraphicMouseMove',
    GRAPHIC_MOUSE_OVER: 'Deck.GraphicMouseOver',
    GRAPHIC_MOUSE_OUT: 'Deck.GraphicMouseOut',
    GRAPHIC_MOUSE_UP: 'Deck.GraphicMouseUp',
    GRAPHIC_KEY_UP: 'Deck.GraphicKeyUp',
    GRAPHIC_KEY_DOWN: 'Deck.GraphicKeyDown',
};
